# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Daily News

on:
  schedule:
  - cron: "0 14 * * *"
  workflow_dispatch:

env:
  SMTP_HOST: ${{ secrets.SMTP_HOST}}
  SMTP_PORT: ${{ secrets.SMTP_PORT}}
  SMTP_USER: ${{ secrets.SMTP_USER}}
  SMTP_PASS: ${{ secrets.SMTP_PASS}}

jobs:
  report:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: node app/sendEmail.mjs
